accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import PassChangeForm, PassResetConfirmForm, PassResetForm

app_name = 'accounts'

urlpatterns = [
    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='accounts/password_change_form.html',
        form_class=PassChangeForm
        ),
        name="passchange"
    ),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name="accounts/password_change_done.html",
    ), name="password_change_done"),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name="accounts/password_reset_done.html"
    ), name="password_reset_done"),

    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name = 'accounts/password_reset_form.html',
        form_class = PassResetForm,
        ),
        name='password_reset'
    ),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html',
        form_class=PassResetConfirmForm
        ),
        name='password_reset_confirm'
    ),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html',
    ), name='password_reset_complete'),

    path('sign-up', views.SignUpView.as_view(), name="sign-up"),
    path('sign-in', views.SignInView.as_view(), name="sign-in"),
    path('sign-out', views.sign_out, name="sign-out"),
    path('profile/delete/', views.delete_user, name='deleteuser'),
    path('profile/', views.profile_view, name='profile'),
    path('activate/<slug:uidb64>/<slug:token>/', views.activate, name='activate'),
    path('fav', views.favourite_add, name='favourite_add'),
    path('save_post/', views.FavouriteList.as_view(), name='save_post'),
    path('like/', views.like, name='like'),
    path('delete/', views.delete_user, name="delete_user"),
]

blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('search/', views.post_search, name="search"),
    path('<slug>/', views.PostDetailView.as_view(), name='detail'),
    path('category/<str:category>/',  views.CategoryView.as_view(), name='category'),
    path('tag/<str:tag_name>/', views.TagArticlesListView.as_view(), name='tag'),
    path('<int:year>/<int:month>/', views.ArticleMonthArchiveView.as_view(month_format='%m'), name="archive_month"),
]

blog/models.py
import datetime

from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models
from django.db.models.deletion import CASCADE
from django.urls import reverse
from django.utils import timezone
from django.utils.text import Truncator, slugify
from meta.models import ModelMeta
from mptt.models import MPTTModel, TreeForeignKey
from taggit.managers import TaggableManager

from .utils import count_words, read_time, user_directory_path

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=110)
    description = models.TextField(blank=True)

    def save(self, *args, **kwargs):
        name = self.name.lower()
        self.name = name
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("blog:category", kwargs={"category": self.name})

class Post(ModelMeta, models.Model):
    blog_id = models.CharField(max_length=100, null=False, blank=False)
    title = models.CharField(max_length=250,null=False, blank=False)
    slug = models.SlugField()
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    tags = TaggableManager(blank=True)
    image = models.ImageField(upload_to=user_directory_path, blank=True)
    image_credit = models.CharField(max_length=250, null=True, blank=True)
    excerpt = models.TextField(blank=True)
    content = RichTextUploadingField(config_name='default')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')

    pub_date = models.DateTimeField(null=True, blank=True, default=timezone.now)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    favourites = models.ManyToManyField(User, related_name='favourite', default=None, blank=True)
    likes = models.ManyToManyField(User, related_name='like', blank=True, default=None)
    like_count = models.BigIntegerField(default="0")
    status = models.BooleanField(default=False)
    views = models.PositiveIntegerField(default=0)
    count_words = models.CharField(max_length=50, default=0)
    read_time = models.CharField(max_length=50, default=0)

    encodings = models.TextField(default=None, blank=True)
    similarity_score = models.FloatField(default=0.0)
    deleted = models.BooleanField(default=False)

    class META:
        unique_together = ("title",)
        ordering = ('-pub_date')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        self.count_words = count_words(self.content)
        self.read_time = read_time(self.content)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"slug": self.slug})


class Comment(MPTTModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    content = models.TextField()
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    pub_date = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)

    class MPTTMeta:
        order_insertion_by = ['pub_date']

    def __str__(self):
        return self.content


blog/forms.py
from django import forms
from mptt.forms import TreeNodeChoiceField

from .models import Category, Comment


class CommentForm(forms.ModelForm):
    parent = TreeNodeChoiceField(queryset=Comment.objects.all())

    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['parent'].widget.attrs.update({'class': 'd-none'})
        self.fields['parent'].label = ''
        self.fields['parent'].required = False
    class Meta:
        model = Comment
        fields = ('name', 'parent', 'email', 'content')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'col-sm-12', 'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'col-sm-12', 'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
        }
    
    
class PostSearchForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['c'].widget.attrs.update({'class': 'custom-select mr-2'})
        self.fields['c'].label = ''
        self.fields['q'].widget.attrs.update({'data-toggle': 'dropdown'})
        self.fields['q'].widget.attrs.update({'autocomplete': 'off'})
        
    query_category = Category.objects.all().order_by('name')
    q = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control dropdown-toggle menudd'}), label='')

    c = forms.ModelChoiceField(query_category, required=False)

blog/views.py
from django.contrib import messages
from django.core import serializers
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count, Q, Sum
from django.http import Http404, JsonResponse
from django.shortcuts import redirect, render
from django.utils import timezone
from django.utils.translation import gettext as _
from django.views.generic import DetailView, ListView, MonthArchiveView
from meta.views import Meta
from taggit.models import Tag

from memories.mixins import form_errors
import numpy as np
from sklearn import metrics

from .forms import CommentForm, PostSearchForm
from .models import Category, Post
from .utils import get_similarity

result = _("Error")
message = _("There was an error, please try again!")


def categories(request):
    categories = Category.objects.exclude(name="default")
    context = {
        'categories': categories,
    }
    return context

class HomeView(ListView):
    model = Post 
    template_name = "blog/index.html"
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        return Post.objects.filter(status=True).order_by('-pub_date')
    

class PostDetailView(DetailView, Meta):
    model = Post
    template_name = "blog/detail.html"
    context_object_name = 'post'
    comment_form = CommentForm()

    def get_queryset(self):
        return Post.objects.filter(status=True)
    

    def get_context_data(self, **kwargs):
        post = self.model.objects.get(slug=self.kwargs['slug'])
        if post.image:
            meta = Meta(
                title = post.title,
                description = post.excerpt,
                url = post.get_absolute_url(),
                author = post.author.get_full_name(),
                published_time = post.pub_date,
                modified_time = post.date_updated,
                keywords = [tag for tag in post.tags.all()],
                image = post.image.url,
                image_object = {
                    'url': post.image.url,
                    'type': 'some/mime',
                    'width': '100',
                    'height': '100',
                    'alt': post.image_credit
                },
                extra_props = {
                    'viewport': 'width=device-width, initial-scale=1.0, minimum-scale=1.0'
                },
                extra_custom_props=[
                    ('http-equiv', 'Content-Type', 'text/html; charset=UTF-8'),
                ],
                use_schemaorg = True,
                use_twitter = True,
                use_og = True,
                use_twitter_tag = True,
                use_facebook = True,
                use_title_tag = True,
            )
        else:
            meta = Meta(
                use_schemaorg = True,
                use_twitter = True,
                use_og = True,
                use_twitter_tag = True,
                use_facebook = True,
                use_title_tag = True,
                title = post.title,
                description = post.excerpt,
                author = post.author.get_full_name(),
                og_author = post.author.get_full_name(),
                published_time = post.pub_date,
                modified_time = post.date_updated,
                keywords = [tag for tag in post.tags.all()],
                
                extra_props = {
                    'viewport': 'width=device-width, initial-scale=1.0, minimum-scale=1.0'
                },
                extra_custom_props=[
                    ('http-equiv', 'Content-Type', 'text/html; charset=UTF-8'),
                ],
                
            )

        session_key = f"viewed_article {self.object.slug}"
        if not self.request.session.get(session_key, False):
            self.object.views += 1
            self.object.save()
            self.request.session[session_key] = True

        fav = bool
        if post.favourites.filter(id=self.request.user.id).exists():
            fav = True

        like = bool
        if post.likes.filter(id=self.request.user.id).exists():
            like = True

        allcomments = post.comments.filter(status=True)
        
        page = self.request.GET.get('page', 1)
        paginator = Paginator(allcomments, 4)
        try:
            comments = paginator.page(page)
        except PageNotAnInteger:
            comments = paginator.page(1)
        except EmptyPage:
            comments = paginator.page(paginator.num_pages)

        user_comment = None
        
        kwargs = self.kwargs
        context = super().get_context_data(**kwargs)
        context['meta'] = meta
        context["fav"] = fav
        context["like"] = like
        context["post"] = post
        context["allcomments"] = allcomments
        context["comments"] = comments
        context["comment_form"] = self.comment_form
        context["related_posts"] = self.model.objects.filter(category=self.object.category, status=True).order_by('?')[:5]
        return context

    def get_related_activities(self):
        queryset = self.object.activity_rel.all()
        paginator = Paginator(queryset, 3)  # paginate_by
        page = self.request.GET.get('page')
        activities = paginator.get_page(page)
        return activities

    def post(self, request, *args, **kwargs):
        post = self.model.objects.get(slug=self.kwargs['slug'])
        new_comment = None
        self.comment_form = CommentForm(request.POST)
        if self.comment_form.is_valid():
            
            if self.request.is_ajax():
                new_comment = self.comment_form.save(commit=False)
                new_comment.post = post
                new_comment.save()

                self.object = self.get_object()
                context = super(DetailView, self).get_context_data(**kwargs)
                context['comment_form'] = self.comment_form
                if new_comment is not None:
                    result = "Success"
                    message = _("Thank you! your comments will be approved by us immediately.")
                else:
                    message = form_errors(self.comment_form)
                data = {'result': result, 'message': message}
                return JsonResponse(data)
            new_comment = self.comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()

            self.object = self.get_object()
            context = super(DetailView, self).get_context_data(**kwargs)
            context['comment_form'] = self.comment_form
            messages.success(self.request, _("Thank you! Your comments will be approved by us immediately."))
            return redirect(request.META['HTTP_REFERER'])


class CategoryView(ListView, Meta):
    model = Post
    template_name = "blog/category.html"
    context_object_name = "catlist"
    paginate_by = 10

    def get_queryset(self):
        category = self.kwargs['category']
        return self.model.objects.filter(category__name=category).filter(pub_date__lte=timezone.now()).order_by('-pub_date')
    
    def get_context_data(self, **kwargs):
        popular = self.model.objects.filter(status=True, pub_date__range=[timezone.now() - timezone.timedelta(15), timezone.now()]).annotate(Sum('views')).order_by('-views')[:3]
        context = super().get_context_data(**kwargs)
        context['popular_list'] = popular
        context['allcategories'] = Category.objects.all().annotate(posts_count=Count('post'))
        context['tags'] = Tag.objects.all()
        context['title'] = self.kwargs['category']
        context['all_posts'] = self.model.objects.order_by('pub_date')
        category = Category.objects.get(name=self.kwargs['category'])
        meta = Meta(
            title = category.name,
            description = category.description,
            use_schemaorg = True,
            use_twitter = True,
            use_og = True,
            use_twitter_tag = True,
            use_facebook = True,
            use_title_tag = True,
        )
        context['meta'] = meta
        return context


def post_search(request):
    form = PostSearchForm()
    q = ''

    if 'q' in request.GET:
        form = PostSearchForm(request.GET)
        if form.is_valid():
            q = form.cleaned_data['q']
            c = form.cleaned_data['c']
        query_text = q

        posts = Post.objects.all()
        
        similarity_post_id = get_similarity(query_text)
        results = posts.filter(blog_id__in=similarity_post_id)


    return render(request, 'blog/search.html', {'form':form,'q':q, 'results':results })


class TagArticlesListView(ListView):
    """
        List posts related to a tag.
    """
    model = Post
    paginate_by = 10
    context_object_name = 'posts_taglist'
    template_name = 'blog/tag_posts_list.html'

    def get_queryset(self):
        """
            Filter Posts by tag_name
        """

        tag_name = self.kwargs.get('tag_name', '')

        if tag_name:
            tag_articles_list = self.model.objects.filter(tags__name__in=[tag_name], status=True).order_by('-pub_date')
            return tag_articles_list
    
    def get_context_data(self, **kwargs):
        popular = self.model.objects.filter(status=True, pub_date__range=[timezone.now() - timezone.timedelta(7), timezone.now()]).annotate(Sum('views')).order_by('-views')[:3]
        context = super().get_context_data(**kwargs)
        context['popular_list'] = popular
        context['allcategories'] = Category.objects.all().annotate(posts_count=Count('post'))
        context['tags'] = Tag.objects.all()
        context['title'] = self.kwargs['tag_name']

blog/templates/blog/snippets/favicons.html
{% load static %}

<link rel="apple-touch-icon" sizes="180x180" href="{% static 'blog/img/favicons/apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'blog/img/favicons/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'blog/img/favicons/favicon-16x16.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'blog/img/favicons/android-chrome-192x192.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'blog/img/favicons/android-chrome-512x512.png' %}">
<link rel="icon" type="image/png" href="{% static 'blog/img/favicons/favicon-32x32.png' %}" sizes="32x32">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'blog/img/favicons/favicon.ico' %}">

blog/templates/blog/snippets/footer.html
{% load static i18n %}

<div class="footer" role="contentinfo" itemscope itemtype="http://schema.org/WPFooter">
    <div class="wrap">
        <div class="wrap_float">
            <div class="footer-content">
                <div class="logo" itemprop="copyrightHolder" itemscope itemtype="http://schema.org/Person" itemprop="name">Memories</div>
                <div class="wrap-center">
                    <div class="socials">
                        <a class="soc-link" href="https://web.facebook.com/da.risset", target="_blank">
                            <img src="{% static 'blog/img/facebook-icon.svg' %}" class="img-svg" alt="">
                        </a>
                        <a class="soc-link" href="https://twitter.com/Danangharisset1", target="_blank">
                            <img src="{% static 'blog/img/twitter-soc-icon.svg' %}" class="img-svg" alt="">
                        </a>
                        <a class="soc-link" href="https://id.pinterest.com/dananghariss/" target="_blank">
                            <img src="{% static 'blog/img/pinterest-icon.svg' %}" class="img-svg" alt="">
                        </a>
                    </div>
                    <div class="menu">
                        <ul>
                            <li><a href="mailto:mr.danangharis@gmail.com">Contact Form</a></li>
                            <li><a href="https://github.com/danangharissetiawan" target="_blank">Github</a></li>
                            <li><a href="https://risset.me" target="_blank">Portfolio</a></li>
                        </ul>
                    </div>
                </div>
                <div class="footer-right">
                {% if request.user.is_authenticated %}
                <a href="https://www.buymeacoffee.com/darisset" target="_blank" class="login-link">coffee</a>
                {% else %}
                    <a href="{% url 'accounts:sign-up' %}" class="login-link">{% trans "Sign Up" %}</a>
                {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="overlay" id="overlay"></div>

blog/templates/blog/snippets/modal-login.html
{% load static i18n %}

<div style="display: none;">
    <div class="modal modal_default modal_login" id="modal-login">
        <div class="modal_wrap">
            <h2 class="title">{% trans "Sign in" %}</h2>
                <div class="modal-form">
                    <form id="signinform" action="{% url 'accounts:sign-in' %}" method="POST">
                        {% csrf_token %}
                        <div class="input-wrap white-label">
                            {{form_login.username}}
                        </div>
                        <div class="input-wrap white-label password-field">
                            {{form_login.password}}
                            <button class="show-password-btn"></button>
                        </div>
                        <div class="agreement">
                            
                            {{form_login.remember_me}}
                            <label for="remember-1" class="agreement-label">
                                <span>
                                    {% trans "Remember me" %}
                                </span>
                            </label>
                        </div>
                        <button class="btn" type="submit">
                            <span>{% trans "Sign In" %}</span>
                        </button>
                        <div class="authorization-socials">
                            <div class="authorization-socials-variants">
                                <div class="socials">
                                    <div class="soc-link">
                                        <img src="{% static 'blog/img/facebook-icon.svg' %}" class="img-svg" alt="">
                                    </div>
                                    <div class="soc-link">
                                        <img src="{% static 'blog/img/twitter-soc-icon.svg' %}" class="img-svg" alt="">
                                    </div>
                                    <div class="soc-link">
                                        <img src="{% static 'blog/img/behance-icon.svg' %}" class="img-svg" alt="">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-info">
                    <p><a href="{% url 'password_reset' %}">{% trans "Forgot password?" %}</a></p>
                    <p>{% trans "Don’t have an account?" %} <a data-href="#modal-registration" class="getModal">{% trans "Create your own right now." %}</a></p>
                </div>
        </div>
        <div class="modal_close"></div>
    </div>
</div>

{% if form.errors %}
    <div class="bottom-message error-message visible" id="error-message">
        <span>
            {% trans "Error: Username or Password not corret!" %}
        </span>
    </div>
{% endif %}

blog/templates/blog/snippets/navbar.html
{% load static i18n %}

<div class="mobile-panel">
    <div class="wrap">
        <div class="wrap_float">
            <div class="mobile-btn" id="js-menu-open">
                <span></span>
                <span></span>
                <span></span>
            </div>
            <a class="logo" href="{% url 'blog:home' %}">
                Memories
            </a>
            <div class="search-button"></div>
        </div>
    </div>
</div>
<div class="container-wrap--dummy"></div>
<div class="top-panel fixed-scroll-up" id="js-panel" role="navigation" itemscope itemtype="http://schema.org/SiteNavigationElement">
    <div class="wrap">
        <div class="wrap_float">
            <div class="mode-check">
                <input type="checkbox" id="mode-checkbox" class="mode-checkbox-input">
                <label for="mode-checkbox" class="mode-checkbox-label" data-dark-title="Dark Mode" data-light-title="Light Mode"></label>
            </div>
            <div class="wrap-center">
                <a href="{% url 'blog:home' %}" class="logo">
                    Memories
                </a>
                <div class="menu" id="js-menu">
                    <ul>
                        <li>
                            <a itemprop="url" href="{% url 'blog:home' %}" itemprop="name">{% trans "Home" %}</a>
                        </li>
                        <li>
                            <a href="#" itemprop="name">{% trans "Categories" %}</a>
                            <ul>
                                {% for category in categories %}
                                <li><a itemprop="url" href="{% url 'blog:category' category %}" itemprop="name">{{category|title}}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                        {% comment %} <li><a itemprop="url" href="{% url 'blog:home' %}" itemprop="name">{% trans "Portfolio" %}</a></li>
                        <li><a itemprop="url" href="{% url 'shop' %}" itemprop="name">{% trans "Shop" %}</a></li> {% endcomment %}
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        <li>
                        {% for language in languages %}
                            {% comment %} {% if language.code == "en" %}
                                <a href="/{{ language.code }}{{ request.get_full_path|slice:'3:'}}" lang="{{ language.code }}" style="padding-left: 0;"> ENG</a>
                            {% else %} {% endcomment %}
                            
                            <a href="/{{ language.code }}{{ request.get_full_path|slice:'3:' }}" lang="{{ language.code }}" style="padding-left: 0; {% if forloop.last == False %} padding-right: 4px;{% endif %}">{{language.code|upper}}{% if forloop.last == False %} / {% endif %}</a>
                            {% comment %} {% endif %} {% endcomment %}
                            
                        {% endfor %}
                        </li>
                    </ul>
                    <ul>
                        {% if request.user.is_authenticated %}
                        <li>
                            <a href="#">{% trans "Account" %}</a>
                            <ul>
                                <li><a href="{% url 'accounts:profile' %}">{% trans "Profile" %}</a></li>
                                <li><a href="{% url 'password_change' %}">{% trans "Change Password" %}</a></li>
                                <li><a href="{% url 'accounts:save_post' %}">{% trans "Favourite" %}</a></li>
                                <li><a href="{% url 'accounts:sign-out' %}" id="signout">{% trans "Sign Out" %}</a></li>
                            </ul>
                        </li>
                        {% else %}
                        <li class="login-li"><a itemprop="url" href="{% url 'accounts:sign-in' %}" class="login-link" itemprop="name">{% trans "Sign In" %}</a></li>
                        {% endif %}
                        
                        </li>
                    </ul>
                </div>
            </div>
            <div class="search-button" id="btn-search"></div>
        </div>
        <div class="socials">
            <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}" target="_blank" class="soc-link">
                <img src="{% static 'blog/img/facebook-icon.svg' %}" class="img-svg" alt="">
            </a>
            <a href="http://twitter.com/share?text={{ article.title }}. &url={{ request.build_absolute_uri }}" target="_blank" class="soc-link">
                <img src="{% static 'blog/img/twitter-soc-icon.svg' %}" class="img-svg" alt="">
            </a>
            <a href="https://www.linkedin.com/sharing/share-offsite/?url={{ request.build_absolute_uri }}"  target="_blank" class="soc-link">
                <img src="{% static 'blog/img/behance-icon.svg' %}" class="img-svg" alt="">
            </a>
        </div>
        <div class="menu-close" id="js-menu-close"></div>
    </div>
</div>

blog/templates/blog/snippets/scripts.html
{% load static compress %}
{% compress js %}

<script src="{% static 'blog/js/jquery.min.js' %}"></script>
<script src="{% static 'blog/js/checkmode.js' %}"></script>
<script src="{% static 'blog/js/slick.min.js' %}"></script>
<script src="{% static 'blog/js/jquery.arcticmodal.min.js' %}"></script>
<script src="{% static 'blog/js/lightgallery.js' %}"></script>
<script src="{% static 'blog/js/jquery.mousewheel.min.js' %}"></script>
<script src="{% static 'blog/js/device.min.js' %}"></script>
<script src="{% static 'blog/js/jquery.placeholder.label.js' %}"></script>
<script src="{% static 'blog/js/jquery-ui.min.js' %}"></script>
<script src="{% static 'blog/js/toastr.min.js' %}"></script>
<script src="{% static 'blog/js/scripts.js' %}"></script>
<script src="{% static 'blog/js/main.js' %}"></script>

<script>
  var logout_url = "{% url 'accounts:sign-out' %}"
  var loggin_url = "{% url 'accounts:sign-in' %}"
</script>
{% endcompress %}