accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import PassChangeForm, PassResetConfirmForm, PassResetForm

app_name = 'accounts'

urlpatterns = [
    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='accounts/password_change_form.html',
        form_class=PassChangeForm
        ),
        name="passchange"
    ),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name="accounts/password_change_done.html",
    ), name="password_change_done"),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name="accounts/password_reset_done.html"
    ), name="password_reset_done"),

    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name = 'accounts/password_reset_form.html',
        form_class = PassResetForm,
        ),
        name='password_reset'
    ),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html',
        form_class=PassResetConfirmForm
        ),
        name='password_reset_confirm'
    ),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html',
    ), name='password_reset_complete'),

    path('sign-up', views.SignUpView.as_view(), name="sign-up"),
    path('sign-in', views.SignInView.as_view(), name="sign-in"),
    path('sign-out', views.sign_out, name="sign-out"),
    path('profile/delete/', views.delete_user, name='deleteuser'),
    path('profile/', views.profile_view, name='profile'),
    path('activate/<slug:uidb64>/<slug:token>/', views.activate, name='activate'),
    path('fav', views.favourite_add, name='favourite_add'),
    path('save_post/', views.FavouriteList.as_view(), name='save_post'),
    path('like/', views.like, name='like'),
    path('delete/', views.delete_user, name="delete_user"),
]

blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('search/', views.post_search, name="search"),
    path('<slug>/', views.PostDetailView.as_view(), name='detail'),
    path('category/<str:category>/',  views.CategoryView.as_view(), name='category'),
    path('tag/<str:tag_name>/', views.TagArticlesListView.as_view(), name='tag'),
    path('<int:year>/<int:month>/', views.ArticleMonthArchiveView.as_view(month_format='%m'), name="archive_month"),
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from PIL import Image

from .utils import user_directory_path


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    created_on = models.DateTimeField(default=timezone.now)
    updated_on = models.DateTimeField(auto_now=True)

    avatar = models.ImageField(
        upload_to=user_directory_path, 
        default='user/avatar.png', 
        help_text="all uploaded profile photos will be resized to 200 * 200"
    )

    email_confirmed = models.BooleanField(default=False)
    captcha_score = models.FloatField(default=0.0)
    has_profile = models.BooleanField(default=False)

    is_active = models.BooleanField(default=True)
    
    


    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.avatar)
        if img.height > 150 or img.width > 150:
            output_size = (150, 150)
            img.thumbnail(output_size)
            img.save(self.avatar.path)
    

    def __str__(self):
        return f"{self.user.username} Profile"

accounts/views.py
from blog.models import Category, Post
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.db.models import Count, Sum
from django.http import HttpResponse, JsonResponse
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.utils import timezone
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.translation import gettext as _
from django.views.generic import ListView
from django.views.generic.edit import FormView
from taggit.models import Tag

from memories.mixins import AjaxFormMixin, form_errors, recaptcha_validation

from .forms import (AccountProfileForm, AccountsForm, UserLoginForm,
                    UserProfileForm)
from .token import account_activation_token

result = _("Error")
message = _("There was an error, please try again!")


class SignUpView(AjaxFormMixin, FormView):
    """
    Generic FormView with our mixin for sign-up with reCAPTURE security.
    """

    template_name = "accounts/sign_up.html"
    form_class = AccountsForm
    success_url = "{{accounts:sign-in}}"

    # reCAPTURE key required in context
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["recaptcha_site_key"] = settings.RECAPTCHA_PUBLIC_KEY
        return context

    def form_valid(self, form):
        response = super(AjaxFormMixin, self).form_valid(form)
        if self.request.is_ajax():
            token = form.cleaned_data.get('token')
            captcha = recaptcha_validation(token)
            if captcha["success"]:
                user = form.save(commit=False)
                user.email = user.username
                user.save()
                profile = user.profile
                profile.captcha_score = float(captcha["score"])
                profile.is_active = False
                profile.save()
                current_site = get_current_site(self.request)
                subject = _('Activate your Account')
                message_activate = render_to_string('accounts/account_activation_email.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                })
                user.email_user(subject=subject, message=message_activate)

                login(self.request, user,
                      backend='django.contrib.auth.backends.ModelBackend')

                # change result & message on success
                result = _("Success")
                message = _("Thank you for signing up and activation sent")

            data = {'result': result, 'message': message}
            return JsonResponse(data)

        return response


class SignInView(AjaxFormMixin, FormView):
    """
    Generic FormView with our mixin for user sign-in
    """
    template_name = 'accounts/sign_in.html'
    form_class = UserLoginForm
    success_url = 'accounts/profile'

    def form_valid(self, form):
        response = super(AjaxFormMixin, self).form_valid(form)
        if self.request.is_ajax():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            # get remember me data from cleaned_data of form
            remember_me = form.cleaned_data.get('remember_me')
            if not remember_me:
                self.request.session.set_expiry(0)  # if remember me is
                self.request.session.modified = True

            # attempt to authenticate user
            user = authenticate(
                self.request, username=username, password=password)
            if user is not None:
                login(self.request, user,
                      backend='django.contrib.auth.backends.ModelBackend')
                result = _("Success")
                message = _("You are now logged in!")
            else:
                message = form_errors(form)

            data = {'result': result, 'message': message}
            return JsonResponse(data)

        return response


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        profile = user.profile
        profile.email_confirmed = True
        profile.has_profile = True
        profile.save()
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        messages.success(request, _("Success!   Your account is acctive now."))
        return redirect('accounts:sign-in')
    else:
        messages.errors(request, _("Errors! Your account is active"))
        return render(request, 'accounts/activation_invalid.html')


@login_required
def sign_out(request):
    """
    Basic view for user sign out
    """
    logout(request)
    data = {
        'result': 'Success',
        'message': _('You are now logged out')
    }
    return JsonResponse(data)


@login_required
def profile_view(request):
    """
    Function view to allow users to update theri profile
    """

    result = "Errors"
    message = ""

    user_form = UserProfileForm(instance=request.user)
    profile_form = AccountProfileForm(instance=request.user.profile)

    if request.method == 'POST':
        user_form = UserProfileForm(instance=request.user, data=request.POST)
        profile_form = AccountProfileForm(
            data=request.POST, files=request.FILES, instance=request.user.profile)

        if profile_form.is_valid() and user_form.is_valid():
            # obj = profile_form.save()
            # if User.objects.filter(username=obj.username).exclude(username=request.user.username).exists():
            #     result = "Errors"
            #     message = _("Please use another username, that is already taken")
            # else:
            # obj.has_profile = True
            # obj.save()

            profile_form.save()
            user_form.save()
            result = "Success"
            message = _("Your profile has been updated")
        else:
            result = "Error"
            message = form_errors(profile_form)

        data = {'result': result, 'message': message}
        return JsonResponse(data)

    else:

        context = {
            'user_form': user_form,
            'profile_form': profile_form
        }

    return render(request, 'accounts/profile.html', context)


@login_required
def profile(request):
    if request.method == 'POST':
        user_form = UserProfileForm(instance=request.user, data=request.POST)
        profile_form = AccountProfileForm(
            request.POST, request.FILES, instance=request.user.profile)

        if profile_form.is_valid() and user_form.is_valid():
            # new_user_form = user_form.save(commit=False)
            # print(User.objects.filter(email=new_user_form.email))
            # if User.objects.filter(email=new_user_form.email).exclude(email=request.user.email).exists():
            #     messages.error(request, _("Please use another Email, that is already taken"))
            # else:
            messages.success(request, _("Success! Profile updated."))
            user_form.save()
            profile_form.save()

    else:
        user_form = UserProfileForm(instance=request.user)
        profile_form = AccountProfileForm(instance=request.user.profile)
    return render(request, 'accounts/profile.html', {'user_form': user_form, 'profile_form': profile_form})


@login_required
def delete_user(request):

    if request.is_ajax():
        user = User.objects.get(username=request.user)
        user.is_active = False
        user.save()
        result = "Success"
        message = _("Your account has been deleted")

        data = {'result': result, 'message': message}
        return JsonResponse(data)
    else:
        return render(request, 'accounts/delete.html')


class FavouriteList(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'accounts/save_posts.html'
    context_object_name = 'favourite_posts'
    paginate_by = 10

    def get_queryset(self):
        self.queryset = self.model.objects.filter(
            favourites=self.request.user).filter(status=True).order_by('-pub_date')
        return super().get_queryset()

    def get_context_data(self, **kwargs):
        popular = self.model.objects.filter(status=True, pub_date__range=[timezone.now(
        ) - timezone.timedelta(7), timezone.now()]).annotate(Sum('views')).order_by('-views')[:3]
        context = super().get_context_data(**kwargs)
        context['popular_list'] = popular
        context['allcategories'] = Category.objects.all().annotate(
            posts_count=Count('post'))
        context['tags'] = Tag.objects.all()
        context['all_posts'] = self.model.objects.order_by('pub_date')
        return context


@login_required
def favourite_list(request):

    posts = Post.objects.filter(favourites=request.user).filter(
        status=True).order_by('-pub_date')[:5]
    return render(request, 'accounts/save_posts.html', {'favourite_posts': posts})


@ login_required
def like(request):
    if request.POST.get('action') == 'post':
        result = ''
        id = int(request.POST.get('postid'))
        post = get_object_or_404(Post, id=id)

accounts/templates/accounts/activation_invalid.html
{% load i18n %}
{% trans "invalid" %}

accounts/templates/accounts/save_posts.html
{% extends 'blog/base.html' %} {% load i18n %}

{% block title %}{% trans "Favourite Posts" %} - Memories{% endblock title %}

{% block contents %}

<div class="page-wrap archive-page favorites-page with-sidebar">
    <div class="breadcrumbs">
        <div class="wrap wrap-center">
            <div class="wrap_float">
                <a href="{% url 'blog:home' %}">{% trans "Home" %}</a> / <a href="#">{% trans "Account" %}</a> / <span class="current">{% trans "Favourites" %}</span>
            </div>
        </div>
    </div>
    <div class="archive-header">
        <div class="wrap wrap-center">
            <div class="wrap_float">
                <h1 class="page-title">{% trans "Favorites" %}</h1>
            </div>

        </div>
    </div>
    <div class="archive-body">
        <div class="wrap">
            {% if favourite_posts %}
            <div class="page-wrap-content">
                <div class="post-items-list posts-two-columns posts-favourites">
                    {% for post in favourite_posts %}
                    {% if post.image %}
                    <a href="{{ post.get_absolute_url }}" class="post-item post-favourites-item" id="post_fav_id{{ post.id }}">
                        {% if request.user.is_authenticated %}
                        <div id="js-add-to-fav{{post.id}}" class="favorites-tag js-add-to-fav {% if post.favourites %}added {% endif %}" data-id="{{ post.id }}">
                            <i class="is-added bouncy"></i>
                            <i class="not-added bouncy"></i>
                            <span class="fav-overlay"></span>
                        </div>
                        {% endif %}
                        <img src="{{ post.image.url }}" alt="" class="post-bg-img">
                        <div class="post-tags">
                            {% for tag in post.tags.all %}
                            {% if forloop.counter <= 2 %}
                            <div class="tag">{{tag|title}}</div>
                            {% endif %}
                            {% endfor %}
                        </div>
                        <h3 class="post-title">
                            {{ post.title }}
                        </h3>
                        <div class="post-info">
                            <div class="post-author post-info-author">
                                <div class="author-image">
                                    <img src="{{ post.author.profile.avatar.url }}" alt="" class="image-cover">
                                </div>
                                <span>{% if post.author.first_name %}{{ post.author.first_name }} {{ post.author.last_name }}{% else %}{{ post.author.username }}{% endif %}</span>
                            </div>
                            <div class="post-date post-info-date">
                                {{ post.pub_date|date:"d F, Y"}}
                            </div>
                        </div>
                    </a>
                    {% else %}
                    <a href="{{ post.get_absolute_url }}" class="post-item post-favourites-item without-bg" id="post_fav_id{{ post.id }}">
                        {% if request.user.is_authenticated %}
                        <div id="js-add-to-fav{{post.id}}" class="favorites-tag js-add-to-fav {% if post.favourites %}added {% endif %}" data-id="{{ post.id }}">
                            <i class="is-added bouncy"></i>
                            <i class="not-added bouncy"></i>
                            <span class="fav-overlay"></span>
                        </div>
                        {% endif %}
                        <div class="post-tags">
                            {% for tag in post.tags.all %}
                            {% if forloop.counter <= 2 %}
                            <div class="tag">{{tag|title}}</div>
                            {% endif %}
                            {% endfor %}
                        </div>
                        <h3 class="post-title">
                            {{ post.title }}
                        </h3>
                        <div class="post-excerption">
                            {{ post.excerpt|truncatewords:30 }}
                        </div>
                        <div class="post-info">
                            <div class="post-author post-info-author">
                                <div class="author-image">
                                    <img src="{{ post.author.profile.avatar.url }}" alt="" class="image-cover">
                                </div>
                                <span>{% if post.author.first_name %}{{ post.author.first_name }} {{ post.author.last_name }}{% else %}{{ post.author.username }}{% endif %}</span>
                            </div>
                            <div class="post-date post-info-date">
                                {{ post.pub_date|date:"d F, Y"}}
                            </div>
                        </div>
                    </a>
                    {% endif %}
                    {% endfor %}
                </div>
                {% if is_paginated %}
                <div class="pagination centered">
                    <div class="pagination-links">
                        {% for num in page_obj.paginator.page_range %}
                        {% if page_obj.number == num %}
                        <a href="#" class="pag-link current">{{ num }}</a>
                        {% else %}
                        <a href="?page={{num}}" class="pag-link">{{num}}</a>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
                {% endif %}
            </div>
            {% else %}
            <div class="page-wrap-content">
                <h2>
                    {% trans "You don't have any favorite posts yet." %}
                </h2>
            </div>
            {% endif %}
            <div class="page-wrap-sidebar">
                <div class="sidebar">
                    <div class="sidebar-item widget_archive">
                        <div class="sidebar-item-title">{% trans "Archive" %}</div>
                        {% regroup all_posts by pub_date.year as year_list %}
                        <ul>
                            {% for year in year_list %}
                                    {% regroup year.list by pub_date.month as month_list %}
                                    {% for month in month_list %}
                                        <li><a href="{% url 'blog:archive_month' year.grouper month.grouper %}">{{ month.list.0.pub_date|date:'F' }} {{ year.grouper }}</a>({{ month.list|length }})</li>
                                    {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="sidebar-item popular-posts">
                        <h3 class="sidebar-item-title">{% trans "Popular Post" %}</h3>
                        <div class="popular-posts-wrap">
                            {% for popular_post in popular_list %}
                            {% if popular_post.image %}
                            <a href="{{ popular_post.get_absolute_url }}" class="post-item popular-posts-item">
                                <img src="{{ popular_post.image.url }}" alt="" class="post-bg-img">
                                <div class="post-tags">
                                    {% for tag in popular_post.tags.all %}
                                    <div class="tag">{{ tag }}</div>
                                    {% endfor %}
                                </div>
                                <div class="post-title">
                                    {{ popular_post.title|title }}
                                </div>
                                <div class="post-info">
                                    <div class="post-author post-info-author">
                                        <div class="author-image">
                                            <img src="{{ popular_post.author.profile.avatar.url }}" alt="{{ popular_post.author.username }}" class="image-cover">
                                        </div>
                                        <span>{% if popular_post.author.first_name %}{{ popular_post.author.first_name }} {{ popular_post.author.last_name }}{% else %}{{ popular_post.author.username }}{% endif %}</span>
                                    </div>
                                    <div class="post-date post-info-date">
                                        {{ popular_post.pub_date|date:"d F, Y"}}
                                    </div>
                                    <div class="post-views post-info-views">
                                        {{ popular_post.views }}
                                    </div>
                                </div>
                            </a>
                            {% else %}
                            <a href="{{ popular_post.get_absolute_url }}" class="post-item popular-posts-item without-bg">
                                <div class="post-tags">
                                    {% for tag in popular_post.tags.all %}
                                    <div class="tag">{{ tag }}</div>
                                    {% endfor %}
                                </div>
                                <div class="post-title">
                                    {{ popular_post.title|title }}
                                </div>
                                <div class="post-info">
                                    <div class="post-author post-info-author">
                                        <div class="author-image">
                                            <img src="{{ popular_post.author.profile.avatar.url }}" alt="{{ popular_post.author.username }}" class="image-cover">
                                        </div>
                                        <span>{% if popular_post.author.first_name %}{{ popular_post.author.first_name }} {{ popular_post.author.last_name }}{% else %}{{ popular_post.author.username }}{% endif %}</span>
                                    </div>
                                    <div class="post-date post-info-date">
                                        {{ popular_post.pub_date|date:"d F, Y"}}
                                    </div>
                                    <div class="post-views post-info-views">
                                        {{ popular_post.views }}
                                    </div>
                                </div>
                            </a>
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="sidebar-item widget_categories">
                        <h3 class="sidebar-item-title">{% trans "Categories" %}</h3>
                        <ul>
                            {% for cate in allcategories %}
                            <li class="cat-item cat-item-2">
                                <a href="{% url 'blog:category' cate %}">{{cate|title}}</a> ({{cate.posts_count}})
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="sidebar-item widget_tag_cloud">
                        <div class="sidebar-item-title">{% trans "Tag Cloud" %}</div>
                        <div class="tagcloud">
                            {% for tag in tags %}
                            {% if forloop.counter <= 10 %}
                            <a href="{% url 'blog:tag' tag %}" class="tag-cloud-link">#{{ tag }}</a>
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




<div class="bottom-message error-message" id="error-message">
    <span>
        {% trans "Unfortunately the article was successfully removed from favorites." %}
    </span>
</div>

 
{% endblock contents %}

{% block extra_scripts %}
<script>
jQuery(".js-add-to-fav").on("click", function (e) {
        e.preventDefault();
        var fav_id = $(this).attr("data-id");
        $.ajax({
            type: 'GET',
            url: "{% url 'accounts:favourite_add' %}",
            data: {postfavid:fav_id},
            success: function (json) {
                    if (json["result"] == "Success") {
                        var redirect = false
                        setTimeout(function () {
                            jQuery(".js-add-to-fav"+fav_id).toggleClass('added');
                            jQuery("#post_fav_id"+fav_id).remove();
                        }, 2600);
                        
                    }
                    else {
                        var redirect = false
                    }
                    ShowAlert(json["result"], json["message"], json["result"].toLowerCase(), redirect);
                },
                error: function (xhr) {
                    ShowAlert("Error", "There was an error, please try again", "error", false);
                    console.log(xhr.status + ": " + xhr.responseText);
                }
            
            });
    });

</script>
{% endblock extra_scripts %}

accounts/templates/accounts/sign_in.html
{% extends 'accounts/base.html' %} {% load static i18n %}

{% block title %}{% trans "Sign In" %} - Memories{% endblock title %}

{% block contents %}
<div class="page-wrap profile-page">
    <div class="page-wrap-content">
        <div class="breadcrumbs">
            <div class="wrap wrap-center">
                <div class="wrap_float">
                    <a href="{% url 'blog:home' %}">{% trans "Home" %}</a> / <a href="#">{% trans "Account" %}</a> / <span class="current">{% trans "Sign In" %}</span>
                </div>
            </div>
        </div>
        <div class="modal modal_default modal_login" style="margin: 0 auto;">
            <div class="wrap">
                <div class="wrap_float">
                
                    <div class="wrap wrap-center">
                        <h2 class="title">{% trans "Sign in" %}</h2>
                        
                        <div class="modal-form">
                            <form id="signinform" action="{% url 'accounts:sign-in' %}" method="POST">
                                {% csrf_token %}
                                <div class="input-wrap white-label">
                                    {{form.username}}
                                </div>
                                <div class="input-wrap white-label password-field">
                                    {{form.password}}
                                    <button class="show-password-btn"></button>
                                </div>
                                <div class="agreement">
                                    
                                    {{form.remember_me}}
                                    <label for="remember-1" class="agreement-label">
                                        <span>
                                            {% trans "Remember me" %}
                                        </span>
                                    </label>
                                </div>
                                <button class="btn" type="submit">
                                    <span>{% trans "Sign In" %}</span>
                                </button>
                                <div class="authorization-socials">
                                    <div class="authorization-socials-variants">
                                        <div class="socials">
                                            <div class="soc-link">
                                                <img src="{% static 'blog/img/facebook-icon.svg' %}" class="img-svg" alt="">
                                            </div>
                                            <div class="soc-link">
                                                <img src="{% static 'blog/img/twitter-soc-icon.svg' %}" class="img-svg" alt="">
                                            </div>
                                            <div class="soc-link">
                                                <img src="{% static 'blog/img/behance-icon.svg' %}" class="img-svg" alt="">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="modal-info">
                            <p><a href="{% url 'accounts:password_reset' %}">{% trans "Forgot password?" %}</a></p>
                            <p>{% trans "Don’t have an account?" %} <a href="{% url 'accounts:sign-up' %}">{% trans "Create your own right now." %}</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% if messages %}
    {% for message in messages %}
    <div class="bottom-message {{ message.tags }}-message" id="{{ message.tags }}-message">
        <span>
            {{ message|escape }}
        </span>
    </div>
    {% endfor %}
{% endif %}
{% endblock contents %}

{% block extra_scripts %}
<script>
var success_url = "{% url 'accounts:profile' %}"
</script>
<script>
setTimeout(function () {
    jQuery("#success-message").addClass("visible");
}, 1000);

setTimeout(function () {
    jQuery("#success-message").removeClass("visible");
}, 4000);
setTimeout(function () {
    jQuery("#errors-message").addClass("visible");
}, 1000);

setTimeout(function () {
    jQuery("#errors-message").removeClass("visible");
}, 4000);
</script>
{% endblock extra_scripts %}