blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('search/', views.post_search, name="search"),
    path('<slug>/', views.PostDetailView.as_view(), name='detail'),
    path('category/<str:category>/',  views.CategoryView.as_view(), name='category'),
    path('tag/<str:tag_name>/', views.TagArticlesListView.as_view(), name='tag'),
    path('<int:year>/<int:month>/', views.ArticleMonthArchiveView.as_view(month_format='%m'), name="archive_month"),
]

blog/models.py
import datetime

from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models
from django.db.models.deletion import CASCADE
from django.urls import reverse
from django.utils import timezone
from django.utils.text import Truncator, slugify
from meta.models import ModelMeta
from mptt.models import MPTTModel, TreeForeignKey
from taggit.managers import TaggableManager

from .utils import count_words, read_time, user_directory_path

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=110)
    description = models.TextField(blank=True)

    def save(self, *args, **kwargs):
        name = self.name.lower()
        self.name = name
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("blog:category", kwargs={"category": self.name})

class Post(ModelMeta, models.Model):
    blog_id = models.CharField(max_length=100, null=False, blank=False)
    title = models.CharField(max_length=250,null=False, blank=False)
    slug = models.SlugField()
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    tags = TaggableManager(blank=True)
    image = models.ImageField(upload_to=user_directory_path, blank=True)
    image_credit = models.CharField(max_length=250, null=True, blank=True)
    excerpt = models.TextField(blank=True)
    content = RichTextUploadingField(config_name='default')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')

    pub_date = models.DateTimeField(null=True, blank=True, default=timezone.now)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    favourites = models.ManyToManyField(User, related_name='favourite', default=None, blank=True)
    likes = models.ManyToManyField(User, related_name='like', blank=True, default=None)
    like_count = models.BigIntegerField(default="0")
    status = models.BooleanField(default=False)
    views = models.PositiveIntegerField(default=0)
    count_words = models.CharField(max_length=50, default=0)
    read_time = models.CharField(max_length=50, default=0)

    encodings = models.TextField(default=None, blank=True)
    similarity_score = models.FloatField(default=0.0)
    deleted = models.BooleanField(default=False)

    class META:
        unique_together = ("title",)
        ordering = ('-pub_date')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        self.count_words = count_words(self.content)
        self.read_time = read_time(self.content)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"slug": self.slug})


class Comment(MPTTModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    content = models.TextField()
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    pub_date = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)

    class MPTTMeta:
        order_insertion_by = ['pub_date']

    def __str__(self):
        return self.content


blog/forms.py
from django import forms
from mptt.forms import TreeNodeChoiceField

from .models import Category, Comment


class CommentForm(forms.ModelForm):
    parent = TreeNodeChoiceField(queryset=Comment.objects.all())

    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['parent'].widget.attrs.update({'class': 'd-none'})
        self.fields['parent'].label = ''
        self.fields['parent'].required = False
    class Meta:
        model = Comment
        fields = ('name', 'parent', 'email', 'content')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'col-sm-12', 'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'col-sm-12', 'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
        }
    
    
class PostSearchForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['c'].widget.attrs.update({'class': 'custom-select mr-2'})
        self.fields['c'].label = ''
        self.fields['q'].widget.attrs.update({'data-toggle': 'dropdown'})
        self.fields['q'].widget.attrs.update({'autocomplete': 'off'})
        
    query_category = Category.objects.all().order_by('name')
    q = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control dropdown-toggle menudd'}), label='')

    c = forms.ModelChoiceField(query_category, required=False)

blog/views.py
from django.contrib import messages
from django.core import serializers
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count, Q, Sum
from django.http import Http404, JsonResponse
from django.shortcuts import redirect, render
from django.utils import timezone
from django.utils.translation import gettext as _
from django.views.generic import DetailView, ListView, MonthArchiveView
from meta.views import Meta
from taggit.models import Tag

from memories.mixins import form_errors
import numpy as np
from sklearn import metrics

from .forms import CommentForm, PostSearchForm
from .models import Category, Post
from .utils import get_similarity

result = _("Error")
message = _("There was an error, please try again!")


def categories(request):
    categories = Category.objects.exclude(name="default")
    context = {
        'categories': categories,
    }
    return context

class HomeView(ListView):
    model = Post 
    template_name = "blog/index.html"
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        return Post.objects.filter(status=True).order_by('-pub_date')
    

class PostDetailView(DetailView, Meta):
    model = Post
    template_name = "blog/detail.html"
    context_object_name = 'post'
    comment_form = CommentForm()

    def get_queryset(self):
        return Post.objects.filter(status=True)
    

    def get_context_data(self, **kwargs):
        post = self.model.objects.get(slug=self.kwargs['slug'])
        if post.image:
            meta = Meta(
                title = post.title,
                description = post.excerpt,
                url = post.get_absolute_url(),
                author = post.author.get_full_name(),
                published_time = post.pub_date,
                modified_time = post.date_updated,
                keywords = [tag for tag in post.tags.all()],
                image = post.image.url,
                image_object = {
                    'url': post.image.url,
                    'type': 'some/mime',
                    'width': '100',
                    'height': '100',
                    'alt': post.image_credit
                },
                extra_props = {
                    'viewport': 'width=device-width, initial-scale=1.0, minimum-scale=1.0'
                },
                extra_custom_props=[
                    ('http-equiv', 'Content-Type', 'text/html; charset=UTF-8'),
                ],
                use_schemaorg = True,
                use_twitter = True,
                use_og = True,
                use_twitter_tag = True,
                use_facebook = True,
                use_title_tag = True,
            )
        else:
            meta = Meta(
                use_schemaorg = True,
                use_twitter = True,
                use_og = True,
                use_twitter_tag = True,
                use_facebook = True,
                use_title_tag = True,
                title = post.title,
                description = post.excerpt,
                author = post.author.get_full_name(),
                og_author = post.author.get_full_name(),
                published_time = post.pub_date,
                modified_time = post.date_updated,
                keywords = [tag for tag in post.tags.all()],
                
                extra_props = {
                    'viewport': 'width=device-width, initial-scale=1.0, minimum-scale=1.0'
                },
                extra_custom_props=[
                    ('http-equiv', 'Content-Type', 'text/html; charset=UTF-8'),
                ],
                
            )

        session_key = f"viewed_article {self.object.slug}"
        if not self.request.session.get(session_key, False):
            self.object.views += 1
            self.object.save()
            self.request.session[session_key] = True

        fav = bool
        if post.favourites.filter(id=self.request.user.id).exists():
            fav = True

        like = bool
        if post.likes.filter(id=self.request.user.id).exists():
            like = True

        allcomments = post.comments.filter(status=True)
        
        page = self.request.GET.get('page', 1)
        paginator = Paginator(allcomments, 4)
        try:
            comments = paginator.page(page)
        except PageNotAnInteger:
            comments = paginator.page(1)
        except EmptyPage:
            comments = paginator.page(paginator.num_pages)

        user_comment = None
        
        kwargs = self.kwargs
        context = super().get_context_data(**kwargs)
        context['meta'] = meta
        context["fav"] = fav
        context["like"] = like
        context["post"] = post
        context["allcomments"] = allcomments
        context["comments"] = comments
        context["comment_form"] = self.comment_form
        context["related_posts"] = self.model.objects.filter(category=self.object.category, status=True).order_by('?')[:5]
        return context

    def get_related_activities(self):
        queryset = self.object.activity_rel.all()
        paginator = Paginator(queryset, 3)  # paginate_by
        page = self.request.GET.get('page')
        activities = paginator.get_page(page)
        return activities

    def post(self, request, *args, **kwargs):
        post = self.model.objects.get(slug=self.kwargs['slug'])
        new_comment = None
        self.comment_form = CommentForm(request.POST)
        if self.comment_form.is_valid():
            
            if self.request.is_ajax():
                new_comment = self.comment_form.save(commit=False)
                new_comment.post = post
                new_comment.save()

                self.object = self.get_object()
                context = super(DetailView, self).get_context_data(**kwargs)
                context['comment_form'] = self.comment_form
                if new_comment is not None:
                    result = "Success"
                    message = _("Thank you! your comments will be approved by us immediately.")
                else:
                    message = form_errors(self.comment_form)
                data = {'result': result, 'message': message}
                return JsonResponse(data)
            new_comment = self.comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()

            self.object = self.get_object()
            context = super(DetailView, self).get_context_data(**kwargs)
            context['comment_form'] = self.comment_form
            messages.success(self.request, _("Thank you! Your comments will be approved by us immediately."))
            return redirect(request.META['HTTP_REFERER'])


class CategoryView(ListView, Meta):
    model = Post
    template_name = "blog/category.html"
    context_object_name = "catlist"
    paginate_by = 10

    def get_queryset(self):
        category = self.kwargs['category']
        return self.model.objects.filter(category__name=category).filter(pub_date__lte=timezone.now()).order_by('-pub_date')
    
    def get_context_data(self, **kwargs):
        popular = self.model.objects.filter(status=True, pub_date__range=[timezone.now() - timezone.timedelta(15), timezone.now()]).annotate(Sum('views')).order_by('-views')[:3]
        context = super().get_context_data(**kwargs)
        context['popular_list'] = popular
        context['allcategories'] = Category.objects.all().annotate(posts_count=Count('post'))
        context['tags'] = Tag.objects.all()
        context['title'] = self.kwargs['category']
        context['all_posts'] = self.model.objects.order_by('pub_date')
        category = Category.objects.get(name=self.kwargs['category'])
        meta = Meta(
            title = category.name,
            description = category.description,
            use_schemaorg = True,
            use_twitter = True,
            use_og = True,
            use_twitter_tag = True,
            use_facebook = True,
            use_title_tag = True,
        )
        context['meta'] = meta
        return context


def post_search(request):
    form = PostSearchForm()
    q = ''

    if 'q' in request.GET:
        form = PostSearchForm(request.GET)
        if form.is_valid():
            q = form.cleaned_data['q']
            c = form.cleaned_data['c']
        query_text = q

        posts = Post.objects.all()
        
        similarity_post_id = get_similarity(query_text)
        results = posts.filter(blog_id__in=similarity_post_id)


    return render(request, 'blog/search.html', {'form':form,'q':q, 'results':results })


class TagArticlesListView(ListView):
    """
        List posts related to a tag.
    """
    model = Post
    paginate_by = 10
    context_object_name = 'posts_taglist'
    template_name = 'blog/tag_posts_list.html'

    def get_queryset(self):
        """
            Filter Posts by tag_name
        """

        tag_name = self.kwargs.get('tag_name', '')

        if tag_name:
            tag_articles_list = self.model.objects.filter(tags__name__in=[tag_name], status=True).order_by('-pub_date')
            return tag_articles_list
    
    def get_context_data(self, **kwargs):
        popular = self.model.objects.filter(status=True, pub_date__range=[timezone.now() - timezone.timedelta(7), timezone.now()]).annotate(Sum('views')).order_by('-views')[:3]
        context = super().get_context_data(**kwargs)
        context['popular_list'] = popular
        context['allcategories'] = Category.objects.all().annotate(posts_count=Count('post'))
        context['tags'] = Tag.objects.all()
        context['title'] = self.kwargs['tag_name']

blog/templates/blog/archive.html
{% extends 'blog/base.html' %} {% load i18n %}

{% block title %} {{ month|date:"F" }} - Memories {% endblock title %}

{% block contents %}
<div class="page-wrap archive-page with-sidebar">
    <div class="breadcrumbs">
        <div class="wrap wrap-center">
            <div class="wrap_float">
                <a href="{% url 'blog:home' %}">{% trans "Home" %}</a> / <a href="#">{% trans "Archive" %}</a> / <span class="current">{{ month|date:"F" }}</span>
            </div>
        </div>
    </div>

    <div class="archive-header">
        <div class="wrap wrap-center">
            <div class="wrap_float">
                <div class="title-wrap">
                    <h1 class="page-title">{{ month|date:"F" }}</h1>
                    <div class="posts-count">
                        {{object_list.count}} Post{{object_list|pluralize}}
                    </div>
                </div>
                <div class="post-description">
                    {{ catlist.category.description }}
                </div>
            </div>
        </div>
    </div>

    <div class="archive-body">
        <div class="wrap">
            <div class="page-wrap-content">
                <div class="post-items-list posts-grid">
                {% for post in object_list %}
                    {% if post.image %}
                    <a href="{{ post.get_absolute_url }}" class="post-item">
                        <img src="{{ post.image.url }}" alt="{{post.title}}" class="post-bg-img">
                        <div class="post-tags">
                            {% for tag in post.tags.all %}
                            {% if forloop.counter <= 2 %}
                            <div class="tag">{{ tag|title }}</div>
                            {% endif %}
                            {% endfor %}
                        </div>
                        <h3 class="post-title">
                            {{ post.title|title }}
                        </h3>
                        <div class="post-info">
                            <div class="post-author post-info-author">
                                <div class="author-image">
                                    <img src="{{ post.author.profile.avatar.url }}" alt="{{post.title}}" class="image-cover">
                                </div>
                                <span>{% if post.author.first_name %}{{ post.author.first_name }} {{ post.author.last_name }}{% else %}{{ post.author.username }}{% endif %}</span>
                            </div>
                            <div class="post-date post-info-date">
                                {{ post.pub_date|date:"d F, Y"}}
                            </div>
                            <div class="post-views post-info-views">
                                {{ post.views}}
                            </div>
                        </div>
                    </a>
                    {% else %}
                    <a href="{{ post.get_absolute_url }}" class="post-item without-bg">
                        <div class="post-tags">
                            {% for tag in post.tags.all %}
                            {% if forloop.counter <= 2 %}
                            <div class="tag">{{ tag|title }}</div>
                            {% endif %}
                            {% endfor %}
                        </div>
                        <h3 class="post-title">
                            {{ post.title|title }}
                        </h3>
                        <div class="post-excerption">
                            {{ post.excerpt }}
                        </div>
                        <div class="post-info">
                            <div class="post-author post-info-author">
                                <div class="author-image">
                                    <img src="{{ post.author.profile.avatar.url }}" alt="{{ post.author.username }}" class="image-cover">
                                </div>
                                <span>{% if post.author.first_name %}{{ post.author.first_name }} {{ post.author.last_name }}{% else %}{{ post.author.username }}{% endif %}</span>
                            </div>
                            <div class="post-date post-info-date">
                                {{ post.pub_date|date:"d F, Y"}}
                            </div>
                            <div class="post-views post-info-views">
                                {{ post.views }}
                            </div>
                        </div>
                    </a>
                    {% endif %}
                {% empty %}
                <h3>{% trans "There are no post in the categoty." %}</h3>
                {% endfor %}
                </div>
                
                {% if is_paginated %}
                <div class="pagination centered">
                    <div class="pagination-links">
                        {% for num in page_obj.paginator.page_range %}
                        {% if page_obj.number == num %}
                        <a href="#" class="pag-link current">{{ num }}</a>
                        {% else %}
                        <a href="?page={{num}}" class="pag-link">{{num}}</a>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
                {% endif %}

                <div class="articles-controls">
                    {% if previous_month %}
                    <a href="{% url 'blog:archive_month' previous_month|date:"Y" previous_month|date:"m" %}" class="articles-controls-item prev-article">
                        <div class="articles-controls-item-wrapper">
                            <div class="control-direction">{% trans "Back" %}</div>
                            <h3 class="post-title">
                                {{ previous_month|date:"F Y" }}
                            </h3>
                        </div>
                    </a>
                    {% endif %}
                    {% if next_month %}
                    <a href="{% url 'blog:archive_month' next_month|date:"Y" next_month|date:"m" %}" class="articles-controls-item next-article">
                        <div class="articles-controls-item-wrapper">
                            <div class="control-direction">{% trans "Next" %}</div>
                            <h3 class="post-title">
                                {{ next_month|date:"F Y" }}
                            </h3>
                        </div>
                    </a>
                    {% endif %}
                </div>

            </div>
            <div class="page-wrap-sidebar">
                <div class="sidebar">
                    <div class="sidebar-item widget_archive">
                        <div class="sidebar-item-title">{% trans "Archive" %}</div>
                        {% regroup all_posts by pub_date.year as year_list %}
                        <ul>
                            {% for year in year_list %}
                                    {% regroup year.list by pub_date.month as month_list %}
                                    {% for month in month_list %}
                                        <li><a href="{% url 'blog:archive_month' year.grouper month.grouper %}">{{ month.list.0.pub_date|date:'F' }} {{ year.grouper }}</a>({{ month.list|length }})</li>
                                    {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="sidebar-item popular-posts">
                        <h3 class="sidebar-item-title">{% trans "Popular Post" %}</h3>
                        <div class="popular-posts-wrap">
                            {% for popular_post in popular_list %}
                            {% if popular_post.image %}
                            <a href="{{ popular_post.get_absolute_url }}" class="post-item popular-posts-item">
                                <img src="{{ popular_post.image.url }}" alt="{{popular_post.title}}" class="post-bg-img">
                                <div class="post-tags">
                                    {% for tag in popular_post.tags.all %}
                                    <div class="tag">{{ tag }}</div>
                                    {% endfor %}
                                </div>
                                <div class="post-title">
                                    {{ popular_post.title|title }}
                                </div>
                                <div class="post-info">
                                    <div class="post-author post-info-author">
                                        <div class="author-image">
                                            <img src="{{ popular_post.author.profile.avatar.url }}" alt="{{ popular_post.author.username }}" class="image-cover">
                                        </div>
                                        <span>{% if popular_post.author.first_name %}{{ popular_post.author.first_name }} {{ popular_post.author.last_name }}{% else %}{{ popular_post.author.username }}{% endif %}</span>
                                    </div>
                                    <div class="post-date post-info-date">
                                        {{ popular_post.pub_date|date:"d F, Y"}}
                                    </div>
                                    <div class="post-views post-info-views">
                                        {{ popular_post.views }}
                                    </div>
                                </div>
                            </a>
                            {% else %}
                            <a href="{{ popular_post.get_absolute_url }}" class="post-item popular-posts-item without-bg">
                                <div class="post-tags">
                                    {% for tag in popular_post.tags.all %}
                                    <div class="tag">{{ tag }}</div>
                                    {% endfor %}
                                </div>
                                <div class="post-title">
                                    {{ popular_post.title|title }}
                                </div>
                                <div class="post-info">
                                    <div class="post-author post-info-author">
                                        <div class="author-image">
                                            <img src="{{ popular_post.author.profile.avatar.url }}" alt="{{ popular_post.author.username }}" class="image-cover">
                                        </div>
                                        <span>{% if popular_post.author.first_name %}{{ popular_post.author.first_name }} {{ popular_post.author.last_name }}{% else %}{{ popular_post.author.username }}{% endif %}</span>
                                    </div>
                                    <div class="post-date post-info-date">
                                        {{ popular_post.pub_date|date:"d F, Y"}}
                                    </div>
                                    <div class="post-views post-info-views">
                                        {{ popular_post.views }}
                                    </div>
                                </div>
                            </a>
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="sidebar-item widget_categories">
                        <h3 class="sidebar-item-title">{% trans "Categories" %}</h3>
                        <ul>
                            {% for cate in allcategories %}
                            <li class="cat-item cat-item-2">
                                <a href="{% url 'blog:category' cate %}">{{cate|title}}</a> ({{cate.posts_count}})
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="sidebar-item widget_tag_cloud">
                        <div class="sidebar-item-title">{% trans "Tag Cloud" %}</div>
                        <div class="tagcloud">
                            {% for tag in tags %}
                            {% if forloop.counter <= 10 %}
                            <a href="{% url 'blog:tag' tag %}" class="tag-cloud-link">#{{ tag }}</a>
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>
<div class="seo-section">
    <div class="wrap wrap-center">
        <div class="wrap_float">
            <h2 class="title">
                {{ catlist.category.name }}
            </h2>
            <div class="section-content wp-content">
                <p>
                {{ catlist.category.description }}
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock contents %}

blog/templates/blog/base.html
{% load i18n static meta %}
{% load pwa %}
{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">

<head {% meta_namespaces %}>
    <title>{% block title %}{% endblock title %}</title>
    {% progressive_web_app_meta %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="google-site-verification" content="lQQ5lIBj_SuLnJJLM4LhCpBHYxuXKiyS4pSs2l0PDMc" />
    {% block head_meta %}
        <meta name="twitter:description" content="{% trans 'Get information that is informative, motivating and in accordance with facts. Protect yourself from fraud, and be someone who is open minded.' %}"/>
        <meta name="twitter:card" content="summary" />
        <meta property="og:image" content="{% static 'blog/assets/img/home-bg.jpg' %}" />
        <meta name="description" content="{% trans 'Get information that is informative, motivating and in accordance with facts. Protect yourself from fraud, and be someone who is open minded.' %}" />
        <meta property="og:title" content="Memories" />
        <meta property="og:type" content="website" />
    {% endblock head_meta %}

    {% comment %} <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous"> {% endcomment %}

    {% block header %}{% endblock header %}
    {% include 'blog/snippets/styles.html' %}
    <link rel="stylesheet" href="{% static 'blog/css/code.css' %}">

    {% block extra_styles %}{% endblock extra_styles %}
    
    {% include 'blog/snippets/favicons.html' %}
    
</head>

<body class="transition-none" itemscope itemtype="http://schema.org/WebPage">

    <div class="search-section">
        <div class="wrap">
            <div class="wrap_float">
                <div class="search-form">
                    <form action="{% url 'blog:search' %}"  method="get">
                        <input autocomplete="off" name="q" type="text" class="search-input" placeholder="Search…">
                        <button class="search-submit"></button>
                    </form>
                </div>
                <div class="search-close" id="search-close"></div>
            </div>
        </div>
    </div>

    <div class="container page">
        <div class="container-wrap">
            
            {% include 'blog/snippets/navbar.html' %}
            
            {% block contents %}
                
            {% endblock contents %}

            {% include 'blog/snippets/footer.html' %}
        </div>
    </div>

    {% include 'blog/snippets/scripts.html' %}
    {% block extra_scripts %}{% endblock extra_scripts %}

</body>

</html>